In [1]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import sys

print("Python location:", sys.executable)
print("Pandas version:", pd.__version__)
print("All good!")

Python location: c:\Users\chity\OneDrive\Desktop\Credit-risk-rag-project\credit_risk_env\Scripts\python.exe
Pandas version: 3.0.5
All good!

In [9]:
df_sample = pd.read_csv("data/raw/accepted_2007_to_2018Q4.csv", nrows=1000)
print("Shape:", df_sample.shape)
df_sample.head()

Shape: (1000, 151)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# How many columns do we have, and what are they?
print("Number of columns:", df_sample.shape[1])
print("\nColumn names:")
print(df_sample.columns.tolist())

Number of columns: 151

Column names:
['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low', 'collections_12_mths_ex_med', 'mths_since_last_major_derog', 'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'disbursement_method', 'debt_settlement_flag', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term']

In [1]:
import pandas as pd

chunk_size = 100000  # process 100,000 rows at a time
missing_counts = None
total_rows = 0

for chunk in pd.read_csv("data/raw/accepted_2007_to_2018Q4.csv", 
                           chunksize=chunk_size, low_memory=False):
    if missing_counts is None:
        missing_counts = chunk.isnull().sum()
    else:
        missing_counts += chunk.isnull().sum()
    total_rows += len(chunk)
    print(f"Processed {total_rows} rows so far...", end="\r")

print("\n\nTotal rows processed:", total_rows)

# Convert to percentage missing per column
missing_percent = (missing_counts / total_rows * 100).sort_values(ascending=False)
print(missing_percent)

Processed 2260701 rows so far...

Total rows processed: 2260701
member_id                                     100.000000
orig_projected_additional_accrued_interest     99.617331
hardship_reason                                99.517097
hardship_payoff_balance_amount                 99.517097
hardship_last_payment_amount                   99.517097
                                                 ...
total_rec_int                                   0.001460
disbursement_method                             0.001460
hardship_flag                                   0.001460
debt_settlement_flag                            0.001460
id                                              0.000000
Length: 151, dtype: float64

In [2]:
pd.set_option('display.max_rows', 200)  # let pandas show all 151 rows, not truncate
print(missing_percent)

member_id                                     100.000000
orig_projected_additional_accrued_interest     99.617331
hardship_reason                                99.517097
hardship_payoff_balance_amount                 99.517097
hardship_last_payment_amount                   99.517097
payment_plan_start_date                        99.517097
hardship_type                                  99.517097
hardship_status                                99.517097
hardship_start_date                            99.517097
deferral_term                                  99.517097
hardship_amount                                99.517097
hardship_dpd                                   99.517097
hardship_loan_status                           99.517097
hardship_length                                99.517097
hardship_end_date                              99.517097
settlement_status                              98.485160
debt_settlement_flag_date                      98.485160
settlement_term                                98.485160
settlement_percentage                          98.485160
settlement_date                                98.485160
settlement_amount                              98.485160
sec_app_mths_since_last_major_derog            98.410139
sec_app_revol_util                             95.303050
revol_bal_joint                                95.221836
sec_app_inq_last_6mths                         95.221792
sec_app_num_rev_accts                          95.221792
sec_app_open_acc                               95.221792
sec_app_earliest_cr_line                       95.221792
sec_app_fico_range_high                        95.221792
sec_app_mort_acc                               95.221792
sec_app_open_act_il                            95.221792
sec_app_fico_range_low                         95.221792
sec_app_collections_12_mths_ex_med             95.221792
sec_app_chargeoff_within_12_mths               95.221792
verification_status_joint                      94.880791
dti_joint                                      94.660683
annual_inc_joint                               94.660506
desc                                           94.423632
mths_since_last_record                         84.113069
mths_since_recent_bc_dlq                       77.011511
mths_since_last_major_derog                    74.309960
mths_since_recent_revol_delinq                 67.250910
next_pymnt_d                                   59.509993
mths_since_last_delinq                         51.246715
il_util                                        47.281042
mths_since_rcnt_il                             40.251099
all_util                                       38.323555
open_acc_6m                                    38.313912
inq_last_12m                                   38.313912
total_cu_tl                                    38.313912
open_il_24m                                    38.313868
max_bal_bc                                     38.313868
open_act_il                                    38.313868
open_il_12m                                    38.313868
open_rv_24m                                    38.313868
total_bal_il                                   38.313868
inq_fi                                         38.313868
open_rv_12m                                    38.313868
mths_since_recent_inq                          13.069751
emp_title                                       7.387178
num_tl_120dpd_2m                                6.798334
emp_length                                      6.499754
mo_sin_old_il_acct                              6.153136
bc_util                                         3.366389
percent_bc_gt_75                                3.335779
bc_open_to_buy                                  3.316140
mths_since_recent_bc                            3.248771
pct_tl_nvr_dlq                                  3.116909
avg_cur_bal                                     3.113149
mo_sin_rcnt_rev_tl_op                           3.110097
num_rev_accts                                   3.110097
mo_sin_old_rev_tl_op                            3.110097
num_op_rev_tl                                   3.110053
num_il_tl                                       3.110053
num_tl_op_past_12m                              3.110053
tot_coll_amt                                    3.110053
num_actv_rev_tl                                 3.110053
total_rev_hi_lim                                3.110053
tot_cur_bal                                     3.110053
num_tl_30dpd                                    3.110053
num_actv_bc_tl                                  3.110053
num_accts_ever_120_pd                           3.110053
num_rev_tl_bal_gt_0                             3.110053
mo_sin_rcnt_tl                                  3.110053
num_tl_90g_dpd_24m                              3.110053
tot_hi_cred_lim                                 3.110053
total_il_high_credit_limit                      3.110053
num_bc_tl                                       3.110053
num_bc_sats                                     2.593134
num_sats                                        2.593134
mort_acc                                        2.214490
total_bal_ex_mort                               2.214490
total_bc_limit                                  2.214490
acc_open_past_24mths                            2.214490
title                                           1.033264
last_pymnt_d                                    0.108816
revol_util                                      0.081170
dti                                             0.077144
pub_rec_bankruptcies                            0.061839
chargeoff_within_12_mths                        0.007874
collections_12_mths_ex_med                      0.007874
tax_liens                                       0.006104
last_credit_pull_d                              0.004645
inq_last_6mths                                  0.002787
delinq_amnt                                     0.002743
total_acc                                       0.002743
open_acc                                        0.002743
earliest_cr_line                                0.002743
pub_rec                                         0.002743
delinq_2yrs                                     0.002743
acc_now_delinq                                  0.002743
annual_inc                                      0.001637
zip_code                                        0.001504
loan_amnt                                       0.001460
funded_amnt                                     0.001460
term                                            0.001460
funded_amnt_inv                                 0.001460
int_rate                                        0.001460
verification_status                             0.001460
out_prncp                                       0.001460
purpose                                         0.001460
pymnt_plan                                      0.001460
loan_status                                     0.001460
issue_d                                         0.001460
grade                                           0.001460
home_ownership                                  0.001460
url                                             0.001460
installment                                     0.001460
sub_grade                                       0.001460
revol_bal                                       0.001460
policy_code                                     0.001460
application_type                                0.001460
last_pymnt_amnt                                 0.001460
last_fico_range_low                             0.001460
addr_state                                      0.001460
collection_recovery_fee                         0.001460
initial_list_status                             0.001460
last_fico_range_high                            0.001460
fico_range_low                                  0.001460
fico_range_high                                 0.001460
out_prncp_inv                                   0.001460
total_pymnt_inv                                 0.001460
total_pymnt                                     0.001460
total_rec_prncp                                 0.001460
recoveries                                      0.001460
total_rec_late_fee                              0.001460
total_rec_int                                   0.001460
disbursement_method                             0.001460
hardship_flag                                   0.001460
debt_settlement_flag                            0.001460
id                                              0.000000
dtype: float64

In [3]:
# Columns we've decided to KEEP, based on our missing-value + data-leakage analysis
keep_columns = [
    # Target variable
    'loan_status',
    # Core application info
    'loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
    'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
    'verification_status', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
    'issue_d',
    # Credit history
    'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'delinq_2yrs',
    'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util',
    'total_acc', 'mort_acc', 'pub_rec_bankruptcies', 'acc_now_delinq',
    # Additional useful, low-missing features
    'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'avg_cur_bal',
    'bc_open_to_buy', 'bc_util', 'mo_sin_old_rev_tl_op', 'num_actv_bc_tl',
    'num_bc_sats', 'num_sats', 'acc_open_past_24mths', 'mort_acc',
    'total_bal_ex_mort', 'total_bc_limit', 'chargeoff_within_12_mths',
    'delinq_amnt', 'tax_liens', 'collections_12_mths_ex_med'
]
# Remove any accidental duplicates in our list
keep_columns = list(dict.fromkeys(keep_columns))

print("Total columns we're keeping:", len(keep_columns))
print(keep_columns)

Total columns we're keeping: 48
['loan_status', 'loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'purpose', 'title', 'zip_code', 'addr_state', 'dti', 'issue_d', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'mort_acc', 'pub_rec_bankruptcies', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'mo_sin_old_rev_tl_op', 'num_actv_bc_tl', 'num_bc_sats', 'num_sats', 'acc_open_past_24mths', 'total_bal_ex_mort', 'total_bc_limit', 'chargeoff_within_12_mths', 'delinq_amnt', 'tax_liens', 'collections_12_mths_ex_med']

In [4]:
df = pd.read_csv(
    "data/raw/accepted_2007_to_2018Q4.csv",
    usecols=keep_columns,
    low_memory=False
)
print("Shape:", df.shape)
print("Memory usage (MB):", round(df.memory_usage(deep=True).sum() / 1024**2, 2))

Shape: (2260701, 48)
Memory usage (MB): 2312.19

In [6]:
df.to_csv("data/processed/loans_trimmed.csv", index=False)
print("Saved successfully!")

Saved successfully!

In [7]:
df_check = pd.read_csv("data/processed/loans_trimmed.csv")
print("Reloaded shape:", df_check.shape)
print("Matches original?", df_check.shape == df.shape)

Reloaded shape: (2260701, 48)
Matches original? True

In [8]:
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,delinq_amnt,mo_sin_old_rev_tl_op,mort_acc,num_actv_bc_tl,num_bc_sats,num_sats,pub_rec_bankruptcies,tax_liens,total_bal_ex_mort,total_bc_limit
0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,...,0.0,128.0,1.0,2.0,2.0,7.0,0.0,0.0,7746.0,2400.0
1,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,...,0.0,192.0,4.0,5.0,13.0,22.0,0.0,0.0,39475.0,79300.0
2,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,...,0.0,184.0,5.0,2.0,2.0,6.0,0.0,0.0,18696.0,6200.0
3,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,...,0.0,87.0,1.0,4.0,8.0,13.0,0.0,0.0,52226.0,62500.0
4,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,...,0.0,210.0,6.0,4.0,5.0,12.0,0.0,0.0,95768.0,20300.0

In [9]:
df.dtypes

loan_amnt                     float64
term                              str
int_rate                      float64
installment                   float64
grade                             str
sub_grade                         str
emp_title                         str
emp_length                        str
home_ownership                    str
annual_inc                    float64
verification_status               str
issue_d                           str
loan_status                       str
purpose                           str
title                             str
zip_code                          str
addr_state                        str
dti                           float64
delinq_2yrs                   float64
earliest_cr_line                  str
fico_range_low                float64
fico_range_high               float64
inq_last_6mths                float64
open_acc                      float64
pub_rec                       float64
revol_bal                     float64
revol_util                    float64
total_acc                     float64
collections_12_mths_ex_med    float64
acc_now_delinq                float64
tot_coll_amt                  float64
tot_cur_bal                   float64
total_rev_hi_lim              float64
acc_open_past_24mths          float64
avg_cur_bal                   float64
bc_open_to_buy                float64
bc_util                       float64
chargeoff_within_12_mths      float64
delinq_amnt                   float64
mo_sin_old_rev_tl_op          float64
mort_acc                      float64
num_actv_bc_tl                float64
num_bc_sats                   float64
num_sats                      float64
pub_rec_bankruptcies          float64
tax_liens                     float64
total_bal_ex_mort             float64
total_bc_limit                float64
dtype: object

In [10]:
df['loan_status'].value_counts()

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64

In [11]:
# Step 1: Define which statuses count as "Paid" (0) vs "Default" (1)

paid_statuses = [
    'Fully Paid',
    'Does not meet the credit policy. Status:Fully Paid'
]
default_statuses = [
    'Charged Off',
    'Default',
    'Does not meet the credit policy. Status:Charged Off'
]
# Step 2: Keep only rows with a FINAL, known outcome (drop Current, Late, In Grace Period)
df_clean = df[df['loan_status'].isin(paid_statuses + default_statuses)].copy()
print("Rows before filtering:", len(df))
print("Rows after filtering:", len(df_clean))
# Step 3: Create the binary target column
df_clean['default'] = df_clean['loan_status'].apply(
    lambda status: 1 if status in default_statuses else 0
)
# Step 4: Check the result
print("\nTarget variable distribution:")
print(df_clean['default'].value_counts())
print("\nAs percentages:")
print(df_clean['default'].value_counts(normalize=True) * 100)

Rows before filtering: 2260701
Rows after filtering: 1348099

Target variable distribution:
default
0    1078739
1     269360
Name: count, dtype: int64

As percentages:
default
0    80.019272
1    19.980728
Name: proportion, dtype: float64

In [12]:
df_clean.to_csv("data/processed/loans_with_target.csv", index=False)
print("Saved!")

Saved!